version: "3.6"
services:
  app:
    container_name: swoole-app
    image: swoole-practice/app:develop
    build:
      context: .
      dockerfile: infra/docker/app/Dockerfile
      target: develop
    volumes:
      - ./:/app
    ports:
    - '9501:9501'
    command: /app/public/server.php
